### PR TITLE
Apply secret manifests first

### PR DESCRIPTION
**Pull request by chuhlomin**
Sometimes missing or outdated secrets may cause deployment to fail.
Since deployment depends on a secret it makes sense to apply secrets first.

### CODE REVIEW

**Comment by mkaminski1988** [comment]
Perhaps we could make the namespace a required param? Wouldn't this would be an issue regardless of the order in which secrets are applied?

**Comment by montmanu** [comment]
> Perhaps we could make the namespace a required param?

Suppose we could explore that.. Initially, my only concern with that would be in how the plugin automatically creates a Namespace resource anytime the `namespace` param is supplied and there are cases where it would probably be preferred to eliminate that apply step from the workflow (e.g., managing labels / annotations on the Namespace resource)

> Wouldn't this would be an issue regardless of the order in which secrets are applied?

I think the Namespace resource would just need to be configured in whichever manifest is applied first.

As an alternative, maybe we should support a new `namespace_template` param (defaulting to the current value) to always apply that first if set?

https://github.com/nytimes/drone-gke/blob/6ac83b93954ef35b0ff2d797b3f58e2d978aa975/main.go#L46-L52

**Comment by mkaminski1988** [comment]
I think this PR is just a band-aid, not a real solution to the correct ordering of manifests. (It's more like a tactical fix for a problem we're currently encountering) What I'm trying to get at is this: will this change break anything? It seems that the namespace resource doesn't get applied in any particular order, in which case the applying the secret before the namespace manifest could happen before this change anyway.

**Comment by montmanu** [comment]
> will this change break anything?

i think it might for users that are omitting the `namespace` param and configuring a `Namespace` resource within their `.kube.yml`.. in that case, the resource's within `.kube.sec.yml` will be referencing a namespace that does not yet exist..

**Comment by msuterski** [comment]
Should the `namespace` plugin param become required if we're worried about it not being available?

**Comment by montmanu** [comment]
@msuterski see my comment in https://github.com/nytimes/drone-gke/pull/120#issuecomment-550409738

consider the case where a user need to include a label on the namespace resource as part of an integration with other tools (e.g., `istio-injection: enabled` for [integration with istio](https://istio.io/docs/setup/additional-setup/sidecar-injection/#deploying-an-app)).. if the `namespace` param is required, the existing implementation would first apply the namespace template embedded within the plugin (removing any existing labels / annotations) before applying the Namespace resource configured within `.kube.yml` (restoring the custom labels / annotations) ..

if we'd prefer to make the `namespace` param required, i think we may want to also add support for customizing the namespace resource template managed by the plugin (e.g., by adding a new `namespace_template` param)

**Comment by msuterski** [comment]
@montmanu could we make the plugin smart enough to check if the NS exists before touching it?

From what I understand the original problem is that we may not be able to apply secrets first because the namespace might not exist (when it's defined, and to be created, in the main spec file).

If the plugin checked if the namespace existed first, and create an empty one if it doesn't, everything else that is defined in the main spec file would/should work just fine.

**Comment by tonglil** [comment]
Hello, I looked over the changes here and it makes sense to me.

By default, the namespace is already being created in an early step, before either secret or non-secret manifests are applied:

https://github.com/nytimes/drone-gke/blob/f25a5b24bae090cb418ea33f23ba771b08727248/main.go#L272-L275

Regarding the use case where one might want to create a custom namespace with labels (instead of using the namespace created by the plugin's `namespace` parameter), they can add that namespace spec into the top of the `.kube.sec.yml` manifest as another yaml document in the same file, which will apply that before applying the rest of the file:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-custom-ns
  labels:
    environment: test
    app: test
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-custom-ns
type: Opaque
data:
  my-data: aGkK
```

I am looking to merge this if there are no objections.

**Comment by montmanu** [comment]
> they can add that namespace spec into the top of the `.kube.sec.yml` manifest

that's effectively a breaking change though, isn't it?

i'm not opposed to it, just think we need to be explicit about it. i personally would have to update several projects i work on where the plugin's namespace parameter is currently omitted and the project's namespace resource is currently configured in `.kube.yml`. i would be somewhat surprised if i were the only one managing namespaces in this way, so just want to make sure that we're clear about the impact of this change.

**Comment by mlclmj** [comment]
I agree that this would be a breaking change if we just reverse the apply order altogether. It seems like a lot of folks have thoughts on how this plugin handles namespaces but that seems like a problem that's bigger than this PR, and maybe something that can be standardized and fixed in the next major version of this plugin. In the meantime, this issue isn't going away by itself and it'd be good to fix this without pulling out the rug from anyone who is using it in the way @montmanu described.

It's not the most elegant, but could we maybe add a config option along the lines of `apply_secrets_first: true` to fix this bug for users who run into this issue but keep the default behaviour as-is for everyone else?

**Pull request closed without merging**
